[sidebar]
    emoji = ""
    subtitle = "根据 zty 定律，每次我的 CF rating max 的下一场都会掉分，又实现了，真是恐怖如斯"
    avatar = "img/avatar.png"

[footer]
    since = 2026
    customText = ""

[article]
    math = true
    readingTime = true

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[colorScheme]
    toggle = true
    default = "auto"
