baseURL = 'https://blog.pages.dev/'
languageCode = 'zh-cn'
title = 'Houseoffan\'s Blog'
theme = 'PaperMod'

[params]
  description = 'Personal blog'

[markup]
  [markup.highlight]
    noClasses = false
